In [1]:
import pandas as pd
import numpy as np

In [2]:
books = pd.read_csv('BX-Books.csv', sep = ';',on_bad_lines = 'skip' ,encoding = 'latin1', low_memory=False)

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
books.shape

(271360, 8)

In [5]:
books = books.iloc[:,[0,1,2,3,4,-1]]
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [6]:
books.rename(columns = {
    'Book-Title': 'title',
    'Book-Author': 'author',
    'Year-Of-Publication': 'year',
    'Publisher': 'publisher',
    'Image-URL-L': 'image_url'
}, inplace = True)

In [7]:
books.head()

,ISBN,title,author,year,publisher,image_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [8]:
users = pd.read_csv('BX-Users.csv', sep = ';',on_bad_lines = 'skip', encoding = 'latin1')
print(users.shape)
users.head()

(278858, 3)

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [9]:
users.rename(columns = {
    'User-ID': 'user_id',
    'Location': 'location',
    'Age': 'age'
}, inplace = True)

In [10]:
users.head()

   user_id                            location   age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [11]:
ratings = pd.read_csv('BX-Book-Ratings.csv', sep = ';',on_bad_lines = 'skip', encoding = 'latin1')
print(ratings.shape)
ratings.head()

(1149780, 3)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [12]:
ratings.rename(columns = {
    'User-ID': 'user_id',
    'Book-Rating': 'rating'
}, inplace = True)

In [13]:
ratings.user_id.value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
276697        1
276706        1
276709        1
276721        1
276723        1
Name: count, Length: 105283, dtype: int64

In [14]:
# Only users who had at least rated more than 200 books
x = ratings.user_id.value_counts() > 200
x

user_id
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
276697    False
276706    False
276709    False
276721    False
276723    False
Name: count, Length: 105283, dtype: bool

In [15]:
x[x].shape

(899,)

In [16]:
y = x[x].index.tolist()
y

[11676,
 198711,
 153662,
 98391,
 35859,
 212898,
 278418,
 76352,
 110973,
 235105,
 230522,
 16795,
 234623,
 36836,
 52584,
 245963,
 204864,
 55492,
 185233,
 171118,
 102967,
 232131,
 227447,
 98741,
 129358,
 60244,
 190925,
 135149,
 231210,
 189835,
 189334,
 69697,
 78783,
 177458,
 172742,
 73394,
 242824,
 269566,
 213350,
 23768,
 238781,
 175003,
 226545,
 36606,
 182085,
 11601,
 148744,
 123981,
 26544,
 43246,
 200674,
 23902,
 274308,
 257204,
 95359,
 166123,
 127233,
 127429,
 162639,
 275970,
 87141,
 172030,
 12538,
 184299,
 238120,
 130474,
 76626,
 236283,
 115120,
 266226,
 93047,
 142524,
 87555,
 254465,
 245827,
 166596,
 51883,
 196077,
 35050,
 265115,
 56959,
 110029,
 228998,
 31315,
 246655,
 271284,
 225087,
 131402,
 56447,
 88733,
 175886,
 40943,
 174304,
 56399,
 251613,
 234828,
 16634,
 158295,
 52614,
 31556,
 156150,
 248718,
 225810,
 35857,
 63714,
 107784,
 167800,
 114414,
 147847,
 274061,
 76499,
 113519,
 182987,
 7346,
 100906,
 224349,
 224764,
 129074,
 252695,
 197659,
 211426,
 265313,
 187145,
 56856,
 127200,
 235842,
 131046,
 170229,
 157273,
 125692,
 78834,
 200226,
 124942,
 3363,
 6251,
 240144,
 195694,
 116599,
 101209,
 146113,
 228764,
 261829,
 217375,
 170518,
 264321,
 193560,
 203968,
 159033,
 69355,
 143253,
 173632,
 251422,
 262399,
 56271,
 6575,
 87746,
 225763,
 242006,
 104636,
 15408,
 21014,
 143175,
 32195,
 174791,
 185384,
 225986,
 26535,
 128835,
 81492,
 114368,
 258185,
 69042,
 249894,
 127359,
 77940,
 138844,
 32773,
 94347,
 37950,
 25981,
 219546,
 205735,
 258152,
 261105,
 49109,
 38023,
 13552,
 181176,
 243077,
 78973,
 28204,
 150124,
 180651,
 149908,
 33974,
 262998,
 210035,
 106225,
 133747,
 206534,
 55548,
 201526,
 30276,
 43842,
 68555,
 110912,
 46398,
 94923,
 268330,
 270713,
 101851,
 190708,
 194669,
 187517,
 129716,
 53174,
 254899,
 61619,
 107021,
 256407,
 69078,
 144531,
 29259,
 60277,
 69971,
 107951,
 186570,
 233911,
 31826,
 3757,
 112001,
 135045,
 72992,
 112026,
 173415,
 265889,
 206979,
 135265,
 16966,
 82893,
 59172,
 231857,
 24921,
 114988,
 156269,
 255489,
 125774,
 150968,
 212923,
 105979,
 130571,
 86243,
 167471,
 20115,
 115490,
 229551,
 210485,
 14521,
 51450,
 30711,
 39646,
 52853,
 125039,
 160819,
 227520,
 256167,
 258534,
 93085,
 126736,
 274004,
 114868,
 112881,
 136205,
 145619,
 203240,
 23872,
 138441,
 113983,
 49144,
 140000,
 89602,
 145451,
 120548,
 236757,
 242106,
 28591,
 225232,
 2276,
 29855,
 277427,
 179978,
 54218,
 221445,
 209516,
 38781,
 217121,
 122429,
 114865,
 32440,
 246617,
 235392,
 30533,
 247447,
 201290,
 236172,
 75860,
 91931,
 143415,
 183995,
 37712,
 145449,
 79186,
 69232,
 146348,
 251394,
 13273,
 95932,
 177072,
 48494,
 94853,
 113270,
 194600,
 269728,
 91832,
 52199,
 111947,
 123883,
 104665,
 196160,
 224138,
 76942,
 27617,
 208829,
 268932,
 16916,
 93363,
 263877,
 178181,
 151806,
 6543,
 17950,
 217740,
 268110,
 11993,
 136382,
 39281,
 162738,
 14422,
 136010,
 205473,
 101876,
 255218,
 209756,
 249862,
 217106,
 254498,
 98297,
 178667,
 252848,
 165319,
 222296,
 241198,
 75591,
 108285,
 170184,
 236340,
 252071,
 51386,
 85656,
 82831,
 223087,
 238557,
 165308,
 25409,
 85526,
 107301,
 246671,
 39467,
 210792,
 250405,
 266866,
 124487,
 168245,
 263460,
 269719,
 40889,
 209373,
 241548,
 100846,
 102702,
 110483,
 133567,
 152249,
 211919,
 226879,
 216683,
 30511,
 89891,
 203799,
 214786,
 216444,
 233917,
 7158,
 105517,
 242299,
 83637,
 131855,
 28523,
 88693,
 188010,
 49889,
 77809,
 234359,
 244349,
 229329,
 266865,
 149907,
 266056,
 212645,
 129851,
 36609,
 155147,
 216012,
 39616,
 162052,
 95193,
 52917,
 148258,
 164533,
 172512,
 260897,
 168387,
 173291,
 42400,
 55490,
 218552,
 84024,
 169233,
 268030,
 32721,
 212965,
 100459,
 122881,
 228681,
 8890,
 105374,
 147451,
 250764,
 206567,
 144131,
 65258,
 141493,
 238961,
 93629,
 8681,
 136252,
 179733,
 227705,
 26516,
 238864,
 41841,
 50225,
 161752,
 70415,
 88677,
 78553,
 247429,
 157247,
 208141,
 147965,
 173684,
 249628,
 163973,
 204591,
 38273,
 273979,
 55187,
 122793,
 182086,
 222050,
 59971,
 168064,
 115003,
 169663,
 67840,
 119575,
 251843,
 150979,
 164465,
 167349,
 253821,
 109574,
 189516,
 208406,
 4385,
 23288,
 95902,
 274301,
 30972,
 182993,
 197775,
 207246,
 191187,
 199772,
 264317,
 131675,
 109955,
 138073,
 229011,
 180586,
 180957,
 264082,
 165232,
 86202,
 201017,
 170513,
 81977,
 244688,
 44728,
 85757,
 79441,
 146230,
 160541,
 21252,
 102647,
 189973,
 12982,
 241980,
 141710,
 254,
 76818,
 52203,
 198699,
 235935,
 96448,
 131837,
 208671,
 8936,
 60707,
 170742,
 10819,
 250184,
 142454,
 55734,
 231827,
 70052,
 71712,
 124078,
 135458,
 224646,
 63394,
 85701,
 15418,
 106816,
 82511,
 92853,
 37567,
 62895,
 263163,
 239594,
 241666,
 155495,
 177432,
 187520,
 169699,
 170634,
 238526,
 156467,
 218608,
 113904,
 148199,
 73651,
 230496,
 245371,
 254971,
 94242,
 81560,
 135831,
 137589,
 236948,
 153621,
 236959,
 259629,
 163804,
 231237,
 247752,
 268032,
 24194,
 153563,
 170575,
 190459,
 193499,
 69808,
 222488,
 70594,
 164675,
 30735,
 51094,
 179744,
 238699,
 271705,
 250962,
 51350,
 25601,
 111174,
 128696,
 178950,
 253556,
 19664,
 151790,
 177090,
 251844,
 264637,
 164828,
 177690,
 192093,
 234597,
 271195,
 150498,
 174216,
 196502,
 203820,
 126492,
 2766,
 53628,
 85993,
 117539,
 174092,
 41700,
 62272,
 63938,
 85426,
 92979,
 147141,
 232945,
 26593,
 53729,
 66680,
 230249,
 239584,
 277639,
 20859,
 225199,
 242083,
 245410,
 69405,
 88283,
 92547,
 115002,
 222941,
 265595,
 129008,
 208410,
 13082,
 26583,
 44595,
 180348,
 16106,
 197364,
 204522,
 238541,
 108352,
 100644,
 110934,
 155219,
 170947,
 183196,
 216466,
 220278,
 95316,
 235282,
 198621,
 204167,
 255092,
 60337,
 80538,
 125519,
 129465,
 180917,
 242409,
 123625,
 127914,
 39773,
 86641,
 124079,
 141901,
 179772,
 201447,
 155014,
 18067,
 140036,
 211430,
 160032,
 38556,
 88937,
 133689,
 246513,
 264031,
 7286,
 31846,
 120093,
 210959,
 27647,
 124363,
 130554,
 28360,
 30487,
 199416,
 98758,
 139742,
 149069,
 149934,
 168464,
 96054,
 164027,
 223154,
 41084,
 47316,
 113817,
 139467,
 244736,
 271448,
 10447,
 137688,
 187256,
 196457,
 201674,
 208568,
 252820,
 92810,
 201768,
 19085,
 95903,
 152186,
 246156,
 114444,
 181687,
 62891,
 104399,
 123790,
 133571,
 145641,
 254206,
 259380,
 49460,
 87974,
 168144,
 30509,
 76223,
 82407,
 257028,
 138097,
 230708,
 266753,
 22625,
 102275,
 144555,
 229313,
 249111,
 76151,
 92652,
 159858,
 213150,
 2977,
 8245,
 81045,
 91203,
 134837,
 154992,
 177374,
 245645,
 6242,
 95991,
 104429,
 114178,
 224430,
 42914,
 190807,
 236058,
 245839,
 43806,
 159376,
 82926,
 163319,
 173835,
 207349,
 72352,
 80683,
 91342,
 21576,
 138578,
 154176,
 206074,
 89192,
 36907,
 209875,
 261037,
 94985,
 117251,
 133868,
 12824,
 109461,
 222204,
 226965,
 55892,
 121726,
 164323,
 267635,
 6563,
 137190,
 240568,
 270820,
 168047,
 205980,
 132083,
 140358,
 6323,
 145165,
 172888,
 7915,
 207499,
 208147,
 258938,
 259260,
 20201,
 143792,
 234721,
 252222,
 277478,
 126604,
 185308,
 256247,
 50730,
 64436,
 131027,
 238545,
 256402,
 225989,
 242646,
 4017,
 102359,
 125203,
 224435,
 229741,
 109901,
 141902,
 178199,
 15957,
 21659,
 35836,
 97874,
 201783,
 8067,
 13850,
 31391,
 35433,
 164096,
 183287,
 196047,
 257700,
 136139,
 142093,
 211847,
 269890,
 87143,
 107453,
 128208,
 153718,
 18401,
 101305,
 141819,
 207782,
 258690,
 95010,
 108005,
 157811,
 163761,
 187170,
 240567,
 50547,
 56360,
 83287,
 110214,
 151589,
 214272,
 246311,
 33145,
 88793,
 116122,
 260183,
 9856,
 28634,
 44296,
 59727,
 73681,
 155916,
 188951,
 268622,
 274808]

In [17]:
ratings = ratings[ratings.user_id.isin(y)]

In [18]:
ratings.head()

      user_id        ISBN  rating
1456   277427  002542730X      10
1457   277427  0026217457       0
1458   277427  003008685X       8
1459   277427  0030615321       0
1460   277427  0060002050       0

In [19]:
# join ratings with book

ratings_with_books = ratings.merge(books, on = 'ISBN')

In [20]:
ratings_with_books.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...

In [21]:
ratings_with_books.groupby('author')['rating'].agg(['mean', 'count']).sort_values(by='count', ascending=False)

                         mean  count
author
Nora Roberts         1.829967   4258
Stephen King         2.955401   4036
James Patterson      1.921640   2195
Mary Higgins Clark   1.633654   2080
Danielle Steel       1.366701   1958
...                       ...    ...
Janet M. Bair        0.000000      1
Janet M. Barclay     5.000000      1
Janet M. Davis       0.000000      1
Janet M. Todd       10.000000      1
ï¿½?ï¿½?ric Holder   0.000000      1

[67164 rows x 2 columns]

In [22]:
ratings_with_books.groupby('year')['rating'].agg(['mean', 'count']).sort_values(by='mean', ascending=False)

                   mean  count
year
1378               10.0      1
2006                9.0      1
2021                8.0      1
1935                5.0      1
1938                5.0      7
...                 ...    ...
2026                0.0      1
2038                0.0      2
1897                0.0      1
DK Publishing Inc   0.0      2
Gallimard           0.0      1

[104 rows x 2 columns]

In [23]:
number_rating = ratings_with_books.groupby('title').rating.count().reset_index()
number_rating

                                                    title  rating
0        A Light in the Storm: The Civil War Diary of ...       2
1                                   Always Have Popsicles       1
2                    Apple Magic (The Collector's series)       1
3        Beyond IBM: Leadership Marketing and Finance ...       1
4        Clifford Visita El Hospital (Clifford El Gran...       1
...                                                   ...     ...
160264  ï¿½?ï¿½?ber die Pflicht zum Ungehorsam gegen d...       3
160265                                  ï¿½?ï¿½?lpiraten.       1
160266                 ï¿½?ï¿½?rger mit Produkt X. Roman.       1
160267                          ï¿½?ï¿½?stlich der Berge.       1
160268                              ï¿½?ï¿½?thique en toc       1

[160269 rows x 2 columns]

In [24]:
number_rating.columns = ['title','num_of_rating']

In [25]:
number_rating.head()

                                               title  num_of_rating
0   A Light in the Storm: The Civil War Diary of ...              2
1                              Always Have Popsicles              1
2               Apple Magic (The Collector's series)              1
3   Beyond IBM: Leadership Marketing and Finance ...              1
4   Clifford Visita El Hospital (Clifford El Gran...              1

In [26]:
final_rating = ratings_with_books.merge(number_rating, on = 'title')

In [27]:
final_rating.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,1
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,1
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,13

In [28]:
# lets take those books which got al least 50 rating of users
final_rating = final_rating[final_rating.num_of_rating >= 50]

final_rating.drop_duplicates(['user_id','title'], inplace = True)

In [29]:
final_rating.shape

(59850, 9)

In [30]:
final_rating.isnull().sum()

user_id          0
ISBN             0
rating           0
title            0
author           0
year             0
publisher        0
image_url        0
num_of_rating    0
dtype: int64

In [31]:
final_rating.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,79

In [32]:
final_rating.nunique()

user_id           888
ISBN             2176
rating             11
title             742
author            584
year               47
publisher         357
image_url        2153
num_of_rating     130
dtype: int64

In [33]:
book_pivot = final_rating.pivot_table(
    index='title',
    columns='user_id',
    values='rating'
)

In [34]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
book_pivot.fillna(0, inplace = True)

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
from scipy.sparse import csr_matrix

In [37]:
book_sparse = csr_matrix(book_pivot)

In [38]:
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14961 stored elements and shape (742, 888)>

In [39]:
type(book_sparse)

scipy.sparse._csr.csr_matrix

In [40]:
from sklearn.neighbors import NearestNeighbors

In [41]:
model = NearestNeighbors(algorithm = 'brute')

In [42]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [66]:
book_pivot.iloc[237,:]

user_id
254       9.0
2276      0.0
2766      0.0
2977      0.0
3363      0.0
         ...
275970    9.0
277427    0.0
277478    0.0
277639    0.0
278418    0.0
Name: Harry Potter and the Chamber of Secrets (Book 2), Length: 888, dtype: float64

In [67]:
distance, suggestion = model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1), n_neighbors = 6)

In [68]:
distance

array([[ 0.        , 67.75691847, 68.05145112, 72.277244  , 75.81556568,
        76.30203143]])

In [69]:
suggestion

array([[237, 238, 240, 241, 184, 536]])

In [70]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall'],
      dtype='str', name='title')

In [72]:
book_names = book_pivot.index
book_names

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='str', name='title', length=742)

In [73]:
book_names[237]

'Harry Potter and the Chamber of Secrets (Book 2)'

In [77]:
np.where(book_pivot.index == '4 Blondes')[0][0]

np.int64(3)

In [78]:
ids = np.where(final_rating.title == 'Harry Potter and the Chamber of Secrets (Book 2)')[0][0]
ids

np.int64(44)

In [79]:
final_rating.iloc[ids].image_url

'http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg'

In [83]:
book_name = []
for book_id in suggestion:
    book_name.append(book_pivot.index[book_id])

In [84]:
book_name

[Index(['Harry Potter and the Chamber of Secrets (Book 2)',
        'Harry Potter and the Goblet of Fire (Book 4)',
        'Harry Potter and the Prisoner of Azkaban (Book 3)',
        'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
        'The Cradle Will Fall'],
       dtype='str', name='title')]

In [85]:
ids_index = []
for name in book_name[0]:
    ids = np.where(final_rating.title == name)[0][0]
    ids_index.append(ids)

In [88]:
ids_index

[np.int64(44),
 np.int64(321),
 np.int64(45),
 np.int64(46),
 np.int64(786),
 np.int64(2297)]

In [90]:
for ids in ids_index:
    url = final_rating.iloc[ids].image_url
    print(url)

http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0439139597.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0439136369.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/043936213X.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0446604232.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0440115450.01.LZZZZZZZ.jpg

In [93]:
import pickle

pickle.dump(model, open('artifacts/model.pkl','wb'))
pickle.dump(book_names, open('artifacts/book_names.pkl','wb'))
pickle.dump(final_rating, open('artifacts/final_rating.pkl','wb'))
pickle.dump(book_pivot, open('artifacts/book_pivot.pkl','wb'))

## Testing model

In [98]:
def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distance, suggestion = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1),n_neighbors = 6)
    
    for i in range(len(suggestion)):
        books = book_pivot.index[suggestion[i]]
        for j in books:
            if j == book_name:
                print(f'You searched {book_name}\n')
                print('The suggestion books are: \n')
            else:
                print(j)

In [100]:
recommend_book('2nd Chance')

You searched 2nd Chance

The suggestion books are:

The Next Accident
The Ghost
Exclusive
Last Man Standing
Unspeakable